security_login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

security_login_check:
    path: /login_check
    defaults: { _controller: AppBundle:Security:loginCheck }

security_logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout }
