app_user_index:
    path: /
    defaults: { _controller: "AppBundle:User:index" }

app_user_edit:
    path: /edit
    defaults: { _controller: "AppBundle:User:edit" }

app_user_delete:
    path: /delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE

app_user_delete_image_profile:
    path: /delete_img_prof
    defaults: { _controller: "AppBundle:User:deleteImgProf" }


