AppBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        urlSlug:
            type: string
            length: 255
            unique: true
    manyToMany:
        products:
            targetEntity: Product
            mappedBy: categories
            cascade: ['all']
