AppBundle\Entity\Product:
    type: entity
    table: product
    repositoryClass: AppBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        price:
            type: decimal
            scale: 2
        description:
            type: text
        stockQuantity:
            type: integer
    manyToMany:
        categories:
            targetEntity: Category
            inversedBy: products
            cascade: ['all']
